In [1]:
import pandas as pd

In [2]:
df = pd.read_json('recent_user_activity.jsonl', lines=True)

In [3]:
df = df.set_index('username')

,posts,comments,timestamps
username,,,
Alarming_Shirt2729,1,1,"[1762723133, 1762723371]"
AutoModerator,0,999,"[1762723138, 1762721212, 1762720179, 176271885..."
Baloo_Cat,1,1,"[1762721209, 1762721241]"
stangravityfalls,1,1,"[1762720177, 1762720217]"
passthepaintbrush,0,10,"[1762722354, 1762375858, 1762325214, 176232573..."
...,...,...,...
rngr666,0,1,[1759737347]
laughlaughmaryjo,0,1,[1760024685]
dopadelic,0,2,"[1759651425, 1759694084]"
A1_JakesSauce,0,2,"[1759668358, 1759680395]"
Relevant-Promise7857,1,2,"[1759603315, 1759603653, 1759639118]"

In [4]:
pd.Timestamp(df.timestamps.apply(min).min(), unit='s')

Timestamp('2025-10-04 18:41:55')

In [5]:
pd.Timestamp(df.timestamps.apply(max).max(), unit='s')

Timestamp('2025-11-09 21:22:51')

In [6]:
df['all_items'] = df.posts+df.comments

In [7]:
df.all_items.describe()

count    3259.000000
mean        4.373121
std        21.840809
min         1.000000
25%         1.000000
50%         2.000000
75%         4.000000
max       999.000000
Name: all_items, dtype: float64

In [8]:
df.loc[['AutoModerator','CritiquePointBot'],:]

,posts,comments,timestamps,all_items
username,,,,
AutoModerator,0,999,"[1762723138, 1762721212, 1762720179, 176271885...",999
CritiquePointBot,1,435,"[1762715488, 1762709938, 1762709917, 176267875...",436

In [9]:
df['oldest_post'] = pd.to_datetime(df.timestamps.apply(min), unit='s')
df['newest_post'] = pd.to_datetime(df.timestamps.apply(max), unit='s')

In [10]:
people_to_message = df.loc[df.all_items<=5,:].sort_values('newest_post', ascending=False).index

In [11]:
len(people_to_message)

2742

# message

In [12]:
import praw

In [22]:
from time import sleep

In [27]:
import random

In [13]:
import os
os.chdir( os.path.dirname( os.getcwd() ) )

In [14]:
reddit = praw.Reddit('cyclistNerd') # using auth info from praw.ini

Version 7.5.0 of praw is outdated. Version 7.8.1 was released Friday October 25, 2024.

In [20]:
MESSAGE_TEXT = \
'''
Hey {username},

I'm cyclistNerd, the moderator of r/photocritique.
I am looking for new members of the subreddit to try out a tool that helps you learn how to write good critiques,
and thought that you might be interested.

We're asking you to use the tool (it's a Google Chrome browser extension) for 10 days to write 10 comments, and
we're raffling off a bunch of nice prizes, including a new camera of your choice! For each comment you write, 
you get an additional raffle ticket.

If you're interested, there are more details [here](https://www.reddit.com/r/photocritique/comments/1opn63v/make_your_critiques_even_better_and_win_a_new/).
Don't hesitate to let me know if you have any questions!
'''

def send_message(username):
    formatted =  MESSAGE_TEXT.format(username=username)
    
    try:
        print(f'Messaging u/{username}...')
        reddit.redditor(username).message(subject='Win a new camera for trying our photocritique tool', message=formatted)
        
    except Exception as e:
        print('Failed.', end='')
        print(e)
        
    finally:
        return

In [26]:
for i, username in enumerate( people_to_message[150:200] ):
    print(f'{i:2d} ', end='')
    send_message(username)
    sleep(5*60+ int(random.uniform(-30, 30)))

 0 Messaging u/thenickfo...
 1 Messaging u/mango_fan...

KeyboardInterrupt: